# Generated by Django 4.2 on 2023-04-21 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('66e64bd3-cde0-4832-81a6-a4bf3c5c6e71'), editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, default='Mixed', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('requirements', models.TextField(default='No Requirements', null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
